### ISSUE TITLE
linux is ok,  win crashes

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaMath/Quadmath.jl#11]
`pkg> add https://github.com/JuliaMath/Quadmath.jl` seems to work on both linux and win
`julia> using Quadmath` seems to work on both linux and win
`julia> Float128(1.0)` works on linux and crashes julia on win -- the REPL window vanishes to fast to read it

**Comment by simonbyrne** [comment]
Yup, it is explained in the README. See #4 as well.

**Comment by JeffreySarnoff** [comment]
thanks for the clarification
