### ISSUE TITLE
This needs to be added to the General registry - doing `]add Quadmath` doesn't find it.

### ISSUE THREAD

**Issue by ScottPJones** [JuliaMath/Quadmath.jl#12]
It looks like Quadmath.jl has not had a release for 2 years, so it's not including in the `JuliaRegistries/General`

**Comment by simonbyrne** [comment]
I was hoping to figure out how to make it work on Windows before I let it wreak havoc upon the world. But that doesn't look likely, so maybe I will.

**Comment by simonbyrne** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/21798
