### ISSUE TITLE
Which QuadMath is being maintained?

### ISSUE THREAD

**Issue by dpo** [JuliaMath/Quadmath.jl#5]
Which of the two QuadMath repositories is being maintained? The README over at HaraldHofstaetter/Quadmath.jl says to install this one, but there haven't been updated in two years. There are several issues and a pull request open at the other repository. If this is no longer maintained, perhaps a call for a maintainer on Discourse is warranted?! This is a very useful package!

Thanks!

**Comment by simonbyrne** [comment]
I agree we should combine them. It is a bit confusing at the moment since Harald Hofstaetter's is the "root" repository, so any pull requests are opened there by default.

@HaraldHofstaetter Do you want to keep maintaining it? Alternatively, we could move it to the JuliaMath org?

**Comment by amontoison** [comment]
Harald Hofstaeffer wasn't active recently, I think it's a good a idea to move it elsewhere.
@vchuravy was also interested to integrate `Float128` directly to Julia (branch `vc/float128`). I don't know if it's still the case?

Meantime, I updated QuadMath for `MPFR 4.0.2` on my branch `mpfr4` (tested with linux).

**Comment by simonbyrne** [comment]
Alright, I've requested that this be detached from the upstream, then I'll move it to JuliaMath

**Comment by simonbyrne** [comment]
All done!
