### ISSUE TITLE
Cannot compute incomplete gamma function for some arguments

### ISSUE THREAD

**Issue by araujoms** [JuliaMath/Quadmath.jl#71]
Essentially the same issue as JuliaMath/DoubleFloats.jl#183

If I call `gamma(Float128(a),x)` for `x >= 3` I get an error, because `gamma` goes to a branch where it uses the function `logabsgamma`, which is not defined for `Float128`. This comes from the deprecation of `lgamma` and its replacement with `loggamma` and `logabsgamma`.

In `DoubleFloats` I fixed this by defining the function in terms of its `BigFloat` version. I could do the same here or, if you prefer, define it in terms of the `Float128` version of `lgamma` with something like
```julia
function logabsgamma(x::Float128)
    sign = x >= 0 ? 1 : 2*mod(ceil(Int64,x),2)-1
    return lgamma(x), sign
end
```
It would also be nice to define a `loggamma` function with the same behaviour of the `SpecialFunctions` one for consistency.

**Comment by RalphAS** [comment]
The version using only Float128 is preferable, and I agree that we should make the related API compatible with SpecialFunctions.
